services:
  todo:
    image: todos:latest
    container_name: todo
    restart: always
    ports:
      - 8080:8080
      - 8081:8081
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081/actuator/health/liveness"]
